// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Alberto on Sun Dec 25 18:48:10 2016 - GUI 3.1.7

extern far cdata gsearch_comm_GeneralOpt;
#ifndef NN_GENERALOPT
#define NN_GENERALOPT
extern far cdata nn_GeneralOpt;
#endif

#define G_comm_GeneralOpt_SILENCE                   (0)
#define G_comm_GeneralOpt_TIME                      (1)
#define G_comm_GeneralOpt_DAY                       (2)
#define G_comm_GeneralOpt_NAME                      (3)
#define G_comm_GeneralOpt_DANCE                     (4)
#define G_comm_GeneralOpt_nota                      (5)

/* ======================= Build Log ========================= */
/* Timestamp:                    Sun Dec 25 18:48:10 2016 */
/* Licensed To:                  Zohar Dvir Yazamut Ltd */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_1:              {time {. t aI1 m .}} */
/* Pronunciation_2:              {day {. d eI1 .}} */
/* Pronunciation_3:              {name {. n eI1 m .}} */
/* Pronunciation_4:              {dance {d eI n s}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  4082 */
/* Grammar Size (bytes):         415 */
/* Total Number of States:       42 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
