; external declaration of sound table:

    .EXTRN (const) SNDTBL_SOUNDS



; external declarations of addresses of sounds for direct access:

    .EXTRN (const) SX_Four
    .EXTRN (const) SX_MainMenu
    .EXTRN (const) SX_One
    .EXTRN (const) SX_PleaseRepeat
    .EXTRN (const) SX_Three
    .EXTRN (const) SX_Two
    .EXTRN (const) SX_GnrlCmdMn
    .EXTRN (const) SX_MotionCtrlMenu
    .EXTRN (const) SX_SettingsMenu
    .EXTRN (const) SX_SmrtMvsMenu
    .EXTRN (const) SX_From
    .EXTRN (const) SX_yccn


; equates defining sounds as entries in the sound table:

SND_Four                .EQU 1
SND_MainMenu            .EQU 2
SND_One                 .EQU 3
SND_PleaseRepeat        .EQU 4
SND_Three               .EQU 5
SND_Two                 .EQU 6
SND_GnrlCmdMn           .EQU 7
SND_MotionCtrlMenu      .EQU 8
SND_SettingsMenu        .EQU 9
SND_SmrtMvsMenu         .EQU 10
SND_From                .EQU 11
SND_yccn                .EQU 12
SND_yccn1               .EQU 13
SND_yccn2               .EQU 14
SND_yccd3               .EQU 15
SND_yccd4               .EQU 16
SND_FromMotion          .EQU 17
SND_FromGeneral         .EQU 18
SND_FromSettings        .EQU 19
SND_FromSmart           .EQU 20

