// external declaration of sound table:

extern far cdata SNDTBL_SOUNDS;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_Four;
extern far cdata SX_MainMenu;
extern far cdata SX_One;
extern far cdata SX_PleaseRepeat;
extern far cdata SX_Three;
extern far cdata SX_Two;
extern far cdata SX_GnrlCmdMn;
extern far cdata SX_MotionCtrlMenu;
extern far cdata SX_SettingsMenu;
extern far cdata SX_SmrtMvsMenu;
extern far cdata SX_From;
extern far cdata SX_yccn;

// constants defining sounds as entries in the sound table:

#define SND_Four                1
#define SND_MainMenu            2
#define SND_One                 3
#define SND_PleaseRepeat        4
#define SND_Three               5
#define SND_Two                 6
#define SND_GnrlCmdMn           7
#define SND_MotionCtrlMenu      8
#define SND_SettingsMenu        9
#define SND_SmrtMvsMenu         10
#define SND_From                11
#define SND_yccn                12
#define SND_yccn1               13
#define SND_yccn2               14
#define SND_yccd3               15
#define SND_yccd4               16
#define SND_FromMotion          17
#define SND_FromGeneral         18
#define SND_FromSettings        19
#define SND_FromSmart           20

