// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Alberto on Tue Apr 11 20:09:28 2017 - GUI 3.1.7

extern far cdata gsearch_trig_MainOpt;
#ifndef NN_MAINOPT
#define NN_MAINOPT
extern far cdata nn_MainOpt;
#endif

#define G_trig_MainOpt_SILENCE                   (0)
#define G_trig_MainOpt_ACTIVATE_VOICE_CONTROL    (1)
#define G_trig_MainOpt_nota                      (2)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Apr 11 20:09:28 2017 */
/* Licensed To:                  zoard afeka ac il */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_0:              {{activate voice control} {@1 k . t I . v eI t . . v >I1 s . . k & n . t 9 oU1 l}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  11061 */
/* Grammar Size (bytes):         458 */
/* Total Number of States:       59 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
