// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Alberto on Sun Dec 25 19:05:07 2016 - GUI 3.1.7

extern far cdata gsearch_comm_SettingsOpt;
#ifndef NN_SETTINGSOPT
#define NN_SETTINGSOPT
extern far cdata nn_SettingsOpt;
#endif

#define G_comm_SettingsOpt_SILENCE                   (0)
#define G_comm_SettingsOpt_NAME                      (1)
#define G_comm_SettingsOpt_TIME                      (2)
#define G_comm_SettingsOpt_DATE                      (3)
#define G_comm_SettingsOpt_nota                      (4)

/* ======================= Build Log ========================= */
/* Timestamp:                    Sun Dec 25 19:05:08 2016 */
/* Licensed To:                  Zohar Dvir Yazamut Ltd */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_1:              {name {. n eI1 m .}} */
/* Pronunciation_2:              {time {. t aI1 m .}} */
/* Pronunciation_3:              {date {. d eI1 t .}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  3866 */
/* Grammar Size (bytes):         331 */
/* Total Number of States:       36 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
