// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Alberto on Sun Dec 25 19:03:20 2016 - GUI 3.1.7

extern far cdata gsearch_comm_SmartOpt;
#ifndef NN_SMARTOPT
#define NN_SMARTOPT
extern far cdata nn_SmartOpt;
#endif

#define G_comm_SmartOpt_SILENCE                   (0)
#define G_comm_SmartOpt_FIRST                     (1)
#define G_comm_SmartOpt_SECOND                    (2)
#define G_comm_SmartOpt_THIRD                     (3)
#define G_comm_SmartOpt_FOURTH                    (4)
#define G_comm_SmartOpt_nota                      (5)

/* ======================= Build Log ========================= */
/* Timestamp:                    Sun Dec 25 19:03:20 2016 */
/* Licensed To:                  Zohar Dvir Yazamut Ltd */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_1:              {first {f 3r1 s t}} */
/* Pronunciation_2:              {second {. s E1 . k & n d .}} */
/* Pronunciation_3:              {third {t eI d}} */
/* Pronunciation_4:              {fourth {f > 9 T}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  5594 */
/* Grammar Size (bytes):         583 */
/* Total Number of States:       58 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
