// HMM Grammar Vocabulary Description file for RSC4
// Version: 25.0
// Copyright (C) 2003-2008 Sensory, Inc. All Rights Reserved.
// Generated by Alberto on Tue Apr 11 20:10:07 2017 - GUI 3.1.7

extern far cdata gsearch_comm_MotionOpt;
#ifndef NN_MOTIONOPT
#define NN_MOTIONOPT
extern far cdata nn_MotionOpt;
#endif

#define G_comm_MotionOpt_SILENCE                   (0)
#define G_comm_MotionOpt_GO_FORWARD                (1)
#define G_comm_MotionOpt_GO_BACKWARD               (2)
#define G_comm_MotionOpt_TURN_LEFT                 (3)
#define G_comm_MotionOpt_TURN_RIGHT                (4)
#define G_comm_MotionOpt_nota                      (5)

/* ======================= Build Log ========================= */
/* Timestamp:                    Tue Apr 11 20:10:07 2017 */
/* Licensed To:                  zoard afeka ac il */
/* QT2SI GUI:                    3.1.7 */
/* Fluent Chip:                  3.1.6 */
/* Quick Synthesis:              0 */
/* Language:                     US English */
/* Acoustic Model:               US English Adults and Kids (464 states) */
/* Pronunciation_1:              {{go forward} {g oU1 . f >1 9 . w & 9 d}} */
/* Pronunciation_2:              {{go backward} {g oU1 . b @1 k . w & 9 d}} */
/* Pronunciation_3:              {{turn left} {. t 3r1 n . . l E1 f t .}} */
/* Pronunciation_4:              {{turn right} {t 3r1 n . . 9 aI1 t}} */
/* End-point Detection:          Stop when end of speech is detected (Best) */
/* Matching Criteria             Match target phrase exactly (Best) */
/* Matching Sensitivity          Normal */
/* Out-of-Vocab Sensitivity:     Normal */
/* Target Device:                RSC-4128 */
/* Acoustic Model Memory Space:  const (bank 0) */
/* Trigger Grammar Memory Space: const (bank 0) */
/* Command Grammar Memory Space: const (bank 0) */
/* On-Chip Templates:            0 */
/* Acoustic Model Size (bytes):  6165 */
/* Grammar Size (bytes):         695 */
/* Total Number of States:       84 */
/* Number of Cyclical States:    0 */
/* Beam:                         45 */
